Updated basepaths for daemons and CLIs

diff --git a/tools/freebsd/etc.rc.d/clid.in b/tools/freebsd/etc.rc.d/clid.in
--- a/tools/freebsd/etc.rc.d/clid.in
+++ b/tools/freebsd/etc.rc.d/clid.in
@@ -6,7 +6,7 @@
 . /etc/rc.subr
 
 # Creating the user:
-#   pw useradd clid -d @LOCALSTATEDIR@/clid -g yans -s /usr/sbin/nologin
+#   pw useradd clid -d /nonexistent -g yans -s /usr/sbin/nologin
 #
 # Add the yansgroup if not already present
 #   pw groupadd yans
@@ -18,29 +18,25 @@
 : ${clid_enable:="no"}
 : ${clid_duser:="clid"}
 : ${clid_dgroup:="yans"}
+: ${ystatedir:="@LOCALSTATEDIR@/yans"}
+: ${clid_basepath:="${ystatedir}/clid"}
 
 name="clid"
 rcvar="clid_enable"
-command="@BINDIR@/clid"
-command_args="-u ${clid_duser} -g ${clid_dgroup} -b @LOCALSTATEDIR@/clid"
+command="@BINDIR@/${name}"
+command_args="-u '${clid_duser}' -g '${clid_dgroup}' -b '${clid_basepath}'"
 start_precmd="clid_precmd"
-pidfile="@LOCALSTATEDIR@/clid/clid.pid"
+pidfile="${clid_basepath}/clid.pid"
 
 clid_precmd()
 {
-  # this is needed for /dev/null
-  if [ ! -d "@LOCALSTATEDIR@/clid" ]; then
-    mkdir -p "@LOCALSTATEDIR@/clid"
-  fi
-
-  chmod 770 "@LOCALSTATEDIR@/clid" || {
-    warn "Failed to set correct permissions of @LOCALSTATEDIR@/clid"
-    return 1
+  install -m 775 -o root -g yans -d "${ystatedir}" || {
+    err 1 "Failed to create ${ystatedir}"
   }
 
-  chown "${clid_duser}:${clid_dgroup}" "@LOCALSTATEDIR@/clid" || {
-    warn "Failed to set correct ownership of @LOCALSTATEDIR@/clid"
-    return 1
+  install -m 770 -o "${clid_duser}" -g "${clid_dgroup}" \
+      -d "${clid_basepath}" || {
+    err 1 "Failed to create ${clid_basepath}"
   }
 
   return 0
diff --git a/tools/freebsd/etc.rc.d/ethd.in b/tools/freebsd/etc.rc.d/ethd.in
--- a/tools/freebsd/etc.rc.d/ethd.in
+++ b/tools/freebsd/etc.rc.d/ethd.in
@@ -6,7 +6,7 @@
 . /etc/rc.subr
 
 # Creating the user:
-#   pw useradd ethd -d @LOCALSTATEDIR@/ethd -g yans -s /usr/sbin/nologin
+#   pw useradd ethd -d /nonexistent  -g yans -s /usr/sbin/nologin
 #
 # Add the yansgroup if not already present
 #   pw groupadd yans
@@ -18,6 +18,8 @@
 : ${ethd_enable:="no"}
 : ${ethd_duser:="ethd"}
 : ${ethd_dgroup:="yans"}
+: ${ystatedir:="@LOCALSTATEDIR@/yans"}
+: ${ethd_basepath:="${ystatedir}/ethd"}
 
 # devfs needs to be mounted inside the chroot of ethd so that
 # it is possible for ethd to access the bpf device. The ID
@@ -29,41 +31,58 @@
 # example ruleset:
 #   [ethdrules=67]
 #   add hide
-#   add path bpf mode 660 unhide
+#   add path bpf user ethd mode 600 unhide
 : ${ethd_devfs_ruleset:=""}
 
 name="ethd"
 rcvar="ethd_enable"
-command="@BINDIR@/ethd"
-command_args="-u ${ethd_duser} -g ${ethd_dgroup} -b @LOCALSTATEDIR@/ethd"
+command="@BINDIR@/${name}"
+command_args="-u '${ethd_duser}' -g '${ethd_dgroup}' -b '${ethd_basepath}'"
 start_precmd="ethd_precmd"
-pidfile="@LOCALSTATEDIR@/ethd/ethd.pid"
+pidfile="${ethd_basepath}/ethd.pid"
+
+mountpoint_is_type() {
+  local _ mountpoint fstype
+  while read -r _ mountpoint fstype _; do
+    if [ "$1" = "$mountpoint" -a "$2" = "$fstype" ]; then
+      return 0
+    fi
+  done <<EOF
+  $(mount -p)
+EOF
+  return 1
+}
 
 ethd_precmd()
 {
-  if [ ! -d "@LOCALSTATEDIR@/ethd/dev" ]; then
-    mkdir -p "@LOCALSTATEDIR@/ethd/dev"
-  fi
+  [ -z "${ethd_devfs_ruleset}" ] && err 1 "No devfs ruleset for ethd"
 
-  # really not sure about this one
-  mount -t devfs devfs @LOCALSTATEDIR@/ethd/dev || {
-    warn "unable to mount devfs"
-    return 1
+  install -m 775 -o root -g yans -d "${ystatedir}" || {
+    err 1 "Failed to create ${ystatedir}"
   }
 
-  chmod 770 @LOCALSTATEDIR@/ethd || {
-    warn "Failed to set correct permissions of @LOCALSTATEDIR@/ethd"
-    return 1
+  install -m 750 -o "${ethd_duser}" -g "${ethd_dgroup}" \
+      -d "${ethd_basepath}" || {
+    err 1 "Failed to create ${clid_basepath}"
   }
 
-  chown "${ethd_duser}:${ethd_dgroup}" @LOCALSTATEDIR@/ethd || {
-    warn "Failed to set correct ownership of @LOCALSTATEDIR@/ethd"
-    return 1
+  # create the devfs mountpoint for bpf device
+  install -m 750 -o "${ethd_duser}" -g "${ethd_dgroup}" \
+      -d "${ethd_basepath}/dev" || {
+    err 1 "Failed to create ${clid_basepath}/dev"
   }
 
-  chown "${ethd_duser}:${ethd_dgroup}" @LOCALSTATEDIR@/ethd/dev/bpf || {
-    warn "Failed to chown bpf device for ethd"
-    return 1
+  # mount devfs if not already mounted
+  mountpoint_is_type "${ethd_basepath}/dev" devfs || {
+    mount -t devfs -o "ruleset=${ethd_devfs_ruleset}" devfs \
+        "${ethd_basepath}/dev" || {
+      err 1 "Failed to mount ethd devfs"
+    }
+
+    # sanity check devfs rule: nonexistent rulesets means mounting with the
+    # default one
+    [ -e "${ethd_basepath}/dev/mem" -o -e "${ethd_basepath}/dev/kmem" ] &&
+      err 1 "a too permissive devfs is mounted for ethd"
   }
 
   return 0
diff --git a/tools/freebsd/etc.rc.d/knegd.in b/tools/freebsd/etc.rc.d/knegd.in
--- a/tools/freebsd/etc.rc.d/knegd.in
+++ b/tools/freebsd/etc.rc.d/knegd.in
@@ -6,7 +6,7 @@
 . /etc/rc.subr
 
 # Creating the user:
-#   pw useradd knegd -d @LOCALSTATEDIR@/knegd -g yans -s /usr/sbin/nologin
+#   pw useradd knegd -d /nonexistent -g yans -s /usr/sbin/nologin
 #
 # Add the yansgroup if not already present
 #   pw groupadd yans
@@ -18,31 +18,25 @@
 : ${knegd_enable:="no"}
 : ${knegd_duser:="knegd"}
 : ${knegd_dgroup:="yans"}
+: ${ystatedir:="@LOCALSTATEDIR@/yans"}
+: ${knegd_basepath:="${ystatedir}/knegd"}
 
 name="knegd"
 rcvar="knegd_enable"
-command="@BINDIR@/knegd"
-command_args="-u ${knegd_duser} -g ${knegd_dgroup} -b @LOCALSTATEDIR@/knegd"
+command="@BINDIR@/${name}"
+command_args="-u '${knegd_duser}' -g '${knegd_dgroup}' -b '${knegd_basepath}'"
 start_precmd="knegd_precmd"
-pidfile="@LOCALSTATEDIR@/knegd/knegd.pid"
+pidfile="${knegd_basepath}/knegd.pid"
 
 knegd_precmd()
 {
-  if [ ! -d "@LOCALSTATEDIR@/knegd" ]; then
-    mkdir -p "@LOCALSTATEDIR@/knegd" || {
-      warn "Failed to create knegd directory"
-      return 1
-    }
-  fi
-
-  chmod 770 "@LOCALSTATEDIR@/knegd" || {
-    warn "Failed to set correct permissions of @LOCALSTATEDIR@/knegd"
-    return 1
+  install -m 775 -o root -g yans -d "${ystatedir}" || {
+    err 1 "Failed to create ${ystatedir}"
   }
 
-  chown "${knegd_duser}:${knegd_dgroup}" "@LOCALSTATEDIR@/knegd" || {
-    warn "Failed to set correct ownership of @LOCALSTATEDIR@/knegd"
-    return 1
+  install -m 770 -o "${knegd_duser}" -g "${knegd_dgroup}" \
+      -d "${knegd_basepath}" || {
+    err 1 "Failed to create ${knegd_basepath}"
   }
 
   return 0
diff --git a/tools/freebsd/etc.rc.d/stored.in b/tools/freebsd/etc.rc.d/stored.in
--- a/tools/freebsd/etc.rc.d/stored.in
+++ b/tools/freebsd/etc.rc.d/stored.in
@@ -6,7 +6,7 @@
 . /etc/rc.subr
 
 # Creating the user:
-#   pw useradd stored -d @LOCALSTATEDIR@/stored -g yans -s /usr/sbin/nologin
+#   pw useradd stored -d /nonexistent -g yans -s /usr/sbin/nologin
 #
 # Add the yansgroup if not already present
 #   pw groupadd yans
@@ -18,31 +18,25 @@
 : ${stored_enable:="no"}
 : ${stored_duser:="stored"}
 : ${stored_dgroup:="yans"}
+: ${ystatedir:="@LOCALSTATEDIR@/yans"}
+: ${stored_basepath:="${ystatedir}/stored"}
 
 name="stored"
 rcvar="stored_enable"
-command="@BINDIR@/stored"
-command_args="-u ${stored_duser} -g ${stored_dgroup} -b @LOCALSTATEDIR@/stored"
+command="@BINDIR@/${name}"
+command_args="-u ${stored_duser} -g ${stored_dgroup} -b '${stored_basepath}'"
 start_precmd="stored_precmd"
-pidfile="@LOCALSTATEDIR@/stored/stored.pid"
+pidfile="${stored_basepath}/stored.pid"
 
 stored_precmd()
 {
-  if [ ! -d "@LOCALSTATEDIR@/stored" ]; then
-    mkdir -p "@LOCALSTATEDIR@/stored" || {
-      warn "Failed to create stored directory"
-      return 1
-    }
-  fi
-
-  chmod 770 "@LOCALSTATEDIR@/stored" || {
-    warn "Failed to set correct permissions of @LOCALSTATEDIR@/stored"
-    return 1
+  install -m 775 -o root -g yans -d "${ystatedir}" || {
+    err 1 "Failed to create ${ystatedir}"
   }
 
-  chown "${stored_duser}:${stored_dgroup}" "@LOCALSTATEDIR@/stored" || {
-    warn "Failed to set correct ownership of @LOCALSTATEDIR@/stored"
-    return 1
+  install -m 770 -o "${stored_duser}" -g "${stored_dgroup}" \
+      -d "${stored_basepath}" || {
+    err 1 "Failed to create ${stored_basepath}"
   }
 
   return 0
